### ISSUE TITLE
Cannot initialise / publish a new project

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#104]
Steps to reproduce: 

* create new empty project 
* VCS -> create git repo
* add a new file and commit it to git
* at this point, I do see the Radicle submenu, *but* I can't see "Initialise" or "Publish" in it. Trying "push" fails with "project is not initialised"

**Comment by gsaslis** [comment]
@Stelios123 This is a blocker for the current iteration.

**Comment by Stelios123** [comment]
You cant see under Git -> Radicle the Share Project On Radicle option?

**Comment by gsaslis** [comment]
@Stelios123 nope! :)
