### ISSUE TITLE
Rad push does not `rad sync` if nothing to push 

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#105]
Steps to reproduce: 

* create new empty project
* VCS -> create git repo
* add a new file and commit it to git
* run `rad init` manually on the command line and fill in necessary info
* Git -> Radicle -> Push only brings up the Git Push dialog and then nothing happens.

**Comment by gsaslis** [comment]
@Stelios123 This is a blocker for the current iteration.

**Comment by Stelios123** [comment]
What do you mean nothing happens? You cant push the changes to the remote repo? You cant see your committed file?

**Comment by gsaslis** [comment]
I mean *nothing happens*. :) 

* there is no relevant output in the git log. 
* I don't see any notification from the radicle plugin. 
* if something else is happening behind the scenes, I don't know how I can verify that. 

Were you not able to reproduce this following the steps above?

**Comment by gsaslis** [comment]
After checking this in more detail with @Stelios123, we found that this behaviour only happens in the case when all commits have already been pushed and the git dialog reports that "Everything is up to date". In that case, no `rad sync` happens.

**Comment by gsaslis** [comment]
with that, let's not consier
