### ISSUE TITLE
Identities list is empty, even if I already have some existing keys

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#106]
`rad auth` on my machine returns about 10 different keys. 

Opening Radicle -> Identities in the Settings brings up an empty list and this is at least confusing. If the plugin only shows identities created through IntelliJ it should at least tell me so, but I would expect to see the list of identities on my machine.

**Comment by gsaslis** [comment]
@Stelios123 I think this is also a blocker for the current iteration.

**Comment by gsaslis** [comment]
@Stelios123 hmmm I guess you still don't have a PR up for this?

**Comment by Stelios123** [comment]
not yet i want to push all the changes in one branch.Btw new clone dialog is in main
