### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#11]
We need to decide on what our CI process will be, what tools we will employ and at what exact steps these need to execute.

For reference, currently, the auto-generated workflows are:

- [x] On each and every pull request (or push to main), the whole build workflow is executed, including verifying the plugin (takes ~4m) and [qodana](https://www.jetbrains.com/qodana/) (first and last time took ~15m, perhaps next time it will take less, need to check) - fixed in #14 

- [x] #16
- [x] #17

**Comment by gsaslis** [comment]
@JChrist I took the liberty of breaking this down into further sub-tasks.

**Comment by gsaslis** [comment]
closing as all sub-tasks completed.
