### ISSUE TITLE
[RTW Screen] - Issues Tab - Search Bar

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#124]
Searches in all issues of all opened radicle projects (results of `/v1/project/${project_id}/issues` for each project). 

* Text search only checks issue titles. 
* By default the issue list should only show **open** issues. The filter should make it possible to see closed issues as well. 

Filters: 

* state
* project
* author
* assignee
* tag

**Comment by gsaslis** [comment]
Depends on https://github.com/radicle-dev/radicle-cli/issues/116

**Comment by Stelios123** [comment]
Result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/274a3966-fe74-4266-a99e-8936aa9d199a

**Comment by gsaslis** [comment]
great stuff @Stelios123 ! 👍🏼
