### ISSUE TITLE
[RTW Screen] - Issues Tab - Issue Listing

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#125]
A single list of issues, regardless of how many projects. 

Issue shows: 

* title
* author 
* tags
* created timestamp

![Image](https://user-images.githubusercontent.com/2420882/200512517-77f87b2e-adcb-41cb-9d69-9d558fd1e5f0.png)

Double-clicking an issue opens the issue view.

**Comment by gsaslis** [comment]
We agreed to also add the tags, in a new line, below the timestamp + author

**Comment by Stelios123** [comment]
Result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/eebce470-1edb-4be4-a2b3-4992bfa08640
