### ISSUE TITLE
[RTW Screen] - Issues tab - Issue overview

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#126]
This issue refers to the bottom part shown in the screenshot - within the Radicle Tool Window.

We only need to **show**: 

* title
* Issue ID
* author
* tags
* assignees
* state 
* created timestamp

Actions: 

* edit assignees
* edit state
* edit tags

We don't need: 
* the info/files/commits tabs
* checkout / branches 
* merge pull request button
* close pull request button

![Image](https://user-images.githubusercontent.com/2420882/200513366-f389d64e-f5b4-43fc-b0c7-3b47ed0dfa51.png)

**Comment by Stelios123** [comment]
Result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/3e60deaf-0639-42cf-9a4e-a930adbea0a8
