### ISSUE TITLE
Issue Activity view

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#127]
This issue is about the top part of the screenshot that opens up like an editor window. 

It shows: 
* comments
  * author (DID)
  * body 

which it pulls from the HTTP API (`/v1/project/${project_id}/issues` )

It allows: 
* adding new comments
* editing the title

It is unclear yet how we will display NEW comments that our node learns about after synchronizing with the network, especially when those have been written **before** other comments we'd already read. 

![Image](https://user-images.githubusercontent.com/2420882/200514186-cf5b1000-21ce-4423-baee-375cf3383e4c.png)

**Comment by Stelios123** [comment]
Result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/f845708d-984f-43d7-9391-ee76faed967c
