### ISSUE TITLE
Patch Proposals Search

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#130]
Search bar should support: 

* text search (title, description and author)
* for this version, it **shouldn't** search for text in comments (this will come as a future improvement)

Filters: 

* state: open closed merged 
* project: $project_name
* author: $author
* tag: $tag 

Autocomplete functionality should be supported only for: `state` and `project` for the time being.

![Image](https://user-images.githubusercontent.com/2420882/201042580-5cc6f893-f8e3-40de-9b2b-40ae31bd6a38.png)

**Comment by gsaslis** [comment]
@Stelios123 I've edited the description here, so I'm removing the size bucket, so you can review and reassign a bucket accordingly (it's fine if it falls in the same bucket).

**Comment by Stelios123** [comment]
What is the autocomplete functionality ?

**Comment by gsaslis** [comment]
@Stelios123 I think that was referring to the fact that if you type `state:` it prompts you with the valid known values for `state`. 

On second thought, I am not sure that makes sense for `project` - because that would imply an API call. Let's focus on `state` for now.

**Comment by Stelios123** [comment]
The above picture is from the previous version of IntelliJ. In the new version you can't write `state:`  instead, you have a dropdown.

![Image](https://user-images.githubusercontent.com/31673488/231138775-d985da70-1fe9-46dd-aff0-2344572b0962.png)

**Comment by gsaslis** [comment]
@Stelios123 dropdown is perfect 👍🏼
