### ISSUE TITLE
Patch Details / Info Tab

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#131]
The Info tab Shows: 

* target branch 
* source branch 
* patch title 
* patch proposal ID
* Tags (i.e. labels) (view only)

This information should be available from `/api/v1/projects/$project_id/patches`, so this issue is about switching to the API from the `rad` CLI commands that we were using pre-heartwood. 

Any additional actions or functionality apart from the ones listed above will go in a separate ticket. 

![Image](https://user-images.githubusercontent.com/2420882/201045111-a3a22e79-da8b-449b-936a-3172a345a0ca.png)

**Comment by gsaslis** [comment]
@Stelios123 should we, perhaps, break this issue down a little ?

"Weeks" sounds like there could be multiple smaller tasks included in here.

**Comment by Stelios123** [comment]
Maybe we can break into Patch Proposals Tab - Patch Overview / Patch proposals Tab -  Info Tab

**Comment by gsaslis** [comment]
@Stelios123 I have heavily edited the description here. Please let me know if what is on the description right now makes sense (and please adjust the size bucket accordingly).

**Comment by JChrist** [comment]
Similarly to #134, there are major differences in the new representation of prs in latest version of ij.
Here is an example of the pr details/info screen (please note it's opening in a new tab in the window):


![Image](https://user-images.githubusercontent.com/1916797/235842280-a2df4e72-260e-41ea-9299-9754b584d56f.png)

**Comment by gsaslis** [comment]
@JChrist the only difference I see between the screenshot above and what is on the description is that labels aren't shown. 

> Here is an example of the pr details/info screen (please note it's opening in a new tab in the window):

You mean the tab in the editor window on the right? 
Am I right in understanding this is the activity view we're implementing in #134 ?

**Comment by JChrist** [comment]
> @JChrist the only difference I see between the screenshot above and what is on the description is that labels aren't shown.
The differences are:
- Labels aren't shown
- It opens each pr in a separate tab, not in the same as the pr listing
- _files_ and _commits_ are shown inline in the info screen, not as separate tabs

> 
> > Here is an example of the pr details/info screen (please note it's opening in a new tab in the window):
> 
> You mean the tab in the editor window on the right? Am I right in understanding this is the activity view we're implementing in #134 ?
Correct, this opens up automatically when opening a specific pr to view details, and can be also manually opened via the `View timeline` link, displayed right after the pr description.

**Comment by JChrist** [comment]
> @JChrist the only difference I see between the screenshot above and what is on the description is that labels aren't shown.
The differences are:
- Labels aren't shown
- It opens each pr in a separate tab, not in the same as the pr listing
- _files_ and _commits_ are shown inline in the info screen, not as separate tabs

> 
> > Here is an example of the pr details/info screen (please note it's opening in a new tab in the window):
> 
> You mean the tab in the editor window on the right? Am I right in understanding this is the activity view we're implementing in #134 ?
Correct, this opens up automatically when opening a specific pr to view details, and can be also manually opened via the `View timeline` link, displayed right after the pr description.

**Comment by gsaslis** [comment]
@JChrist ok, thanks for helping clear that up!

does it make sense to include this new work (to bring the UI up-to-speed with the new intellij UI) as part of this ticket, or do you think we should conclude the previous round of changes first ?

I am not on the latest intellij version, so - from my point of view - this certainly looks like it can wait. Then again, if it's just simpler for us to do, I'm open to the idea.

**Comment by JChrist** [comment]
Well, it certainly isn't simpler, so we could carry on with our current behavior, based on the previous pr appearance, but I think we can skip parts that are going to be dropped when switching to the new ui (e.g. having a separate section to show the labels)

**Comment by gsaslis** [comment]
@JChrist ok sounds like a plan.
