### ISSUE TITLE
Patch Proposal Activity - Listing in Editor Tab

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#134]
Similar to the GitHub plugin, this tab shows:

### Header

* The title of the Patch Proposal 
* The revision number and identifier
* the status of the PP (open, merged, closed, etc.)  
* the author of the PP - and their alias, if I have stored one.
* the datetime when the PP was opened.

### Conversation / Activity: 

* the first entry in the conversation view is always the description added at the time the Patch was opened. 
* the following entries in the conversation view are the comments and/or additional commits, **sorted by the timestamp when they were created* **, as that is returned by the API 
* each comment entry should contain: 
  * `$author_alias (did:...) commented on $date` on the first line
  * the actual comment
  * (no support for suggestions, etc. as of right now)
* each new entry for commits should contain:   
  * `$author_alias (did:...)  commit title` 

We do not yet need to support "Discussions" (that can be resolved/unresolved) as we would need support for that in the underlying model). 

* Note: there is a known issue with this approach: some times "older" comments (in terms of date) - that were written while their author was not connected to the internet -  may appear in the discussion **before** comments that were written **later** (simply because our node didn't know about these comments due to the author having previously been offline). 

This issue is for the initial listing **only**. Actions will be added in separate issues.

Some screenshots from the GitHub plugin follow: 

![Image](https://user-images.githubusercontent.com/2420882/201048287-72db7af4-36c5-4d5b-9097-471aa5abbbc8.png)

![Image](https://user-images.githubusercontent.com/2420882/201058427-89fafc38-3cb7-4941-a9e3-ad48f5d2fc63.png)

**Comment by Stelios123** [comment]
This is the new ui. I suggest to go with it

![Image](https://user-images.githubusercontent.com/31673488/234255205-d9199167-2170-4048-8bef-c2da3d77f80c.png)

**Comment by gsaslis** [comment]
@Stelios123 thanks, but looking at the screenshot above, it's not 100% clear what the differences are. 

Perhaps if you can show a PR that has reviews, so that it becomes a bit more evident what has changed ?

**Comment by Stelios123** [comment]
![Image](https://user-images.githubusercontent.com/31673488/234619875-98d0248c-47ac-4b23-96d8-695ae7f173ce.png)
