### ISSUE TITLE
IntelliJ 2022.3 compatibility

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#141]
Ensure compatibility with latest IntelliJ version. 

Depending on usage statistics, we may also want to consider dropping support for some older versions or deprecating some.
According to https://plugins.jetbrains.com/docs/marketplace/product-versions-in-use-statistics.html : 

> In general, statistics show the following trends:
> 
> It makes sense to support the latest major release, as well as at least two previous major releases (in this case, you are covering the majority of the users — on average, it's somewhat 80%). This % doesn't change from product to product much.
> 
> The latest version of the product is used by roughly 50% of the users (and it does take some time to upgrade to the newest version, especially in the companies, so it may be a bit lower at the moment).
> 
> The latest major release minus three major versions have roughly 10% userbase.

**Comment by Stelios123** [comment]
Here we said that the plugin will only be compatible with the latest version of IntelliJ 2022.3 right? Also to close this task we need new icons for the new UI

**Comment by gsaslis** [comment]
@Stelios123 from what I see written above: 

> It makes sense to support the latest major release, as well as at least two previous major releases 

so, no, we shouldn't _only_ support 2022.3 , right?

**Comment by gsaslis** [comment]
After further discussion with @Stelios123 / @JChrist, we decided to **only** support 2022.3 in 0.3.0 due to the major / breaking changes introduced by Jetbrains in this release. Considering 0.3.0 is only going to be an `alpha` release (due to the `rad` CLI upcoming changes with heartwood - which mean the current version of the plugin cannot rely on a specific version of `rad` to pull all required info that we want to display in the UI), we don't see this as a blocker for 0.3.0. 

Depending on when we have a plugin version that works on heartwood, we can revisit and introduce support for older versions, if it is worth the investment (in terms of % users still on pre-2022.3 versions at that point in time).
