### ISSUE TITLE
IntelliJ "New UI" compatibility

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#142]
Jetbrains has a "New UI" : https://blog.jetbrains.com/idea/2022/05/take-part-in-the-new-ui-preview-for-your-jetbrains-ide/

TODO: 

* document how to show the radicle toolbar icons
* document how to view the radicle menus 
* ensure shortcuts still work
* ensure actions still work  (cmd/ctrl + shift + a) 
* ensure clone / publish / push still work
* fix visual styling (e.g. icons, borders, etc. ) in case something looks out of place

**Comment by Stelios123** [comment]
_First Bullet_



![Image](https://user-images.githubusercontent.com/31673488/211533855-300a0b39-b1bd-4299-81ab-589e8ea54889.png)



![Image](https://user-images.githubusercontent.com/31673488/211533865-7d4433e1-db3b-4273-9947-1af1b3e3a74a.png)

**Comment by Stelios123** [comment]
Fifth Bullet

All actions works as expected

**Comment by gsaslis** [comment]
@Stelios123 ok, if you need something specific for the icons, please reach out to Michalis on Discord.

**Comment by gsaslis** [comment]
otherwise, it sounds like this issue is basically done ?

**Comment by Stelios123** [comment]
Correct

**Comment by Stelios123** [comment]
We can switch icons based on the theme (Light / Dark). I don't know if we can switch icons based on the new/old UI.

**Comment by Stelios123** [comment]
I talk with @micmei and we decided to change the appearance of rad icons only in the new UI. Any objections ? 



![Image](https://user-images.githubusercontent.com/31673488/212076304-7447fb5f-db80-4ece-b43d-23ea5ec37cdb.png)
![Image](https://user-images.githubusercontent.com/31673488/212076305-5fad05c9-8921-471a-8046-84357b0a1a68.png)

**Comment by gsaslis** [comment]
@Stelios123 sounds good to me

(but I admit I didn't quite understand @JChrist 's comment, so we better get a 👍🏼 from him too...)
