### ISSUE TITLE
IJ 2022.3 build warnings

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#145]
```
network/radicle/jetbrains/radiclejetbrainsplugin/listeners/RadicleManagerListener.java:21: warning: [removal] projectOpened(Project) in ProjectManagerListener has been deprecated and marked for removal
    public void projectOpened(Project project) {
                ^
```

```
network/radicle/jetbrains/radiclejetbrainsplugin/dialog/clone/RadCheckoutProvider.java:33: warning: [removal] doCheckout(Project,Listener) in CheckoutProvider has been deprecated and marked for removal
    public void doCheckout(@NotNull Project project, @Nullable Listener listener) {
                ^
```

**Comment by gsaslis** [comment]
@Stelios123 / @JChrist is this still an issue ?

adding to 0.3.0 to ensure it gets fixed / verified.

**Comment by Stelios123** [comment]
I fixed the first warning. For the second one, I don't think there is a function that replaces doCheckout at this moment. Also, doCheckout is also used from other plugins. I think we have to wait a little bit longer for this.

**Comment by gsaslis** [comment]
@Stelios123 you mean `doCheckout` has been deprecated without an alternative being offered? 🤔

**Comment by Stelios123** [comment]
yes, I didn't find another alternative. Also, the git plugin still use this function

**Comment by gsaslis** [comment]
@Stelios123 ok, looking at that in more detail, I see we don't actually **rely** on that function of the interface (our implementation is empty), so, as far as I understand, that means we can ignore that warning. 

When it **is** removed, we will simply delete the empty implementation and we'll be done. 

Am I missing something ?
