### ISSUE TITLE
Add check for Developer Certificate of Origin

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#152]
The "Signed-off-by" line in the commit message attests that the committer agrees to https://developercertificate.org  - essentially ensuring original work (and helping us avoid copyright claims), without imposing a bunch of constraints that Contributor License Agreements (CLAs) typically do - and that I would personally hate to see added to our projects. 

We should a github action that verifies all commits (from now on) have the signed-off-by line.

**Comment by JChrist** [comment]
Awesome!
I think we need some document (e.g. README? or Contributing?) to contain a message that we require each commit to be Signed-off-by iff they agree with dco, similar to what linux and git do.

For example, see git's submitting patches documentation for [sign-off](https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n227)

**Comment by JChrist** [comment]
Sample bots that might do what we need:
DCO: https://github.com/dcoapp/app

Also, (if ever needed) for CLAs:
CLA: https://github.com/contributor-assistant/github-action

**Comment by gsaslis** [comment]
I was recommended this one: https://probot.github.io/apps/dco/

**Comment by gsaslis** [comment]
@JChrist can you please install https://probot.github.io/apps/dco/ ? (I don't have permissions to request installation under the cytechmobile org)

**Comment by JChrist** [comment]
Should be done, please confirm ! :)

**Comment by gsaslis** [comment]
@JChrist looks like I'll have to pass this issue on to you 

![Screenshot 2023-01-18 at 12 24 45 PM](https://user-images.githubusercontent.com/2420882/213147379-aebe441c-c623-4b56-a75a-5297c2e2a5c3.png)

**Comment by gsaslis** [comment]
from https://github.com/cytechmobile/radicle-jetbrains-plugin/settings/installations

**Comment by JChrist** [comment]
should be done, PR #173 shows it in action :)
