### ISSUE TITLE
Document expected `rad` CLI commands

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#170]
We should come up with the CLI commands that would make it easier for our UI to pull all the relevant data and pass this onto the clients team, as input for their CLI design.

**Comment by gsaslis** [comment]
## Patch Listing

Eventually, we need to show the following information: 

* state (open, closed, etc.),
* author (peer identifier, profile name (or some human readable) ), 
* peer branch name,
* commit hash,
* title,
* description, 
* reviewers,
* creation date, 
* last updated date,
* "unread" status (we need to track the "last opened" date)

**Comment by gsaslis** [comment]
## Patch Overview

everything returned in patch listing, PLUS: 

* comments, 
* reviews,
* assigned labels,
* CI check results, 

## Patch Update

* add/edit/delete comment, 
* add/edit/delete review, 
* add/edit/remove reviewers,
* close PP,
* merge PP,
* assign/remove label,

**Comment by Stelios123** [comment]
- We need a command in order to get a list of the identities
- We need a command in order to remove identities (I think this command exists in the 0.7 rad version)

**Comment by gsaslis** [comment]
we have already provided some input informally on zulip and we now have a much more direct connection with the code collab team, so closing this.
