### ISSUE TITLE
Check CLI commands on Heartwood

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#188]
Check CLI commands used by the plugin for broken compatibility: 

- rad inspect
- rad remote

**Comment by Stelios123** [comment]
- Rad inspect will break the feature we have that allows the user to view the radicle project on the browser ( Radicle clone window )
- Also the rad remote command will break the patch proposals feature

**Comment by gsaslis** [comment]
are you still looking for replacements? e.g. would something like `rad web` work for the former?

**Comment by gsaslis** [comment]
not sure what `rad remote` does, but it sounds like there should be another way to find the latter, right?

**Comment by gsaslis** [comment]
@Stelios123 about

- `rad remote` : not 100% sure why we used that and what information it provided, but it seems we can get the patch proposals  from the API: https://github.com/radicle-dev/heartwood/blob/master/radicle-httpd/src/api/v1/projects.rs#L59 
- `rad inspect`: what is the missing piece of information we need there?

**Comment by JChrist** [comment]
Both seem to be obsolete on heartwood.
- `rad inspect` was used to find repo information after pushing/syncing, displayed in the notification (which repo was pushed to which seed node).
- `rad remote` was used as part of patch proposal (simulation) to find if patch proposal peers were tracked and track them if needed.

**Comment by gsaslis** [comment]
@JChrist but `rad inspect` still exists on heartwood: https://github.com/radicle-dev/heartwood/blob/master/radicle-cli/src/commands/inspect.rs

**Comment by JChrist** [comment]
By _obsolete_, I meant for our plugin's purposes, not generally.
