### ISSUE TITLE
Migrate Radicle -> clone to heartwood

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#189]
1. Try: 

* cloning an existing project (from local and remote node)
* creating and cloning our own project 
* with single delegate and multiple delegates 

2. Document what needs to change 
3. Add label with estimate (hours, days, weeks) 
4. Start working on the fixes

**Comment by Stelios123** [comment]
> CHANGES

**Repository URL**
- We have to change the url validation

**Radicle**
- I assume we will have to change the current API URL with a new one and also change the parsing in order to get
the RID instead of the urn

**Comment by gsaslis** [comment]
We also need to **remove** the seed node selection in the Clone -> Radicle... window (in line with the changes in #203): 

![Image](https://user-images.githubusercontent.com/2420882/226848852-3d0bbde1-2b4f-4cf2-b874-86c7a26f6b9e.png)

**Comment by gsaslis** [comment]
@Stelios123 let me confirm what you mean here: 

> Repository URL: We have to change the url validation

Are you referring to the seed node ? or the fact that the project id is different?

> I assume we will have to change the current API URL with a new one 

Does #203 cover what you had in mind around that?

> and also change the parsing in order to get the RID instead of the urn

You mean in the API response, right?

> Also maybe we will have to change the pagination

👍
