### ISSUE TITLE
Remove Radicle -> pull

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#190]
1. Try:
* create project X in folder Y
* commit some changes
* push to community node seed.radicle.xyz
* clone in different folder Z
* push some more changes to X from Y
* pull changes from X in Z

2. Document what needs to change
3. Add label with estimate (hours, days, weeks)
4. Start working on the fixes

**Comment by Stelios123** [comment]
There is no pull command

**Comment by gsaslis** [comment]
There is a [fetch](https://github.com/radicle-dev/heartwood/blob/master/radicle-cli/src/commands/fetch.rs) command

**Comment by gsaslis** [comment]
After trying things out further, it seems we should **remove** the radicle pull button / functionality. 

Here is an example of how changes can be pulled and no `rad pull` is required: 

1. Create a new repo: 

```bash
23-03-22 10:08 ➜  alice mkdir project3
23-03-22 10:09 ➜  alice cd project3
23-03-22 10:09 ➜  project3 vi README.md
23-03-22 10:09 ➜  project3 git init
Initialized empty Git repository in /Users/yorgos/dev/playground/web3/radicle/playtime/alice/project3/.git/
23-03-22 10:09 ➜  project3 git:(main) ✗ git add .
23-03-22 10:09 ➜  project3 git:(main) ✗ git commit -m 'babis'
[main (root-commit) d2e3e57] babis
 1 file changed, 1 insertion(+)
 create mode 100644 README.md
23-03-22 10:09 ➜  project3 git:(main) rad init

Initializing local 🌱 project in .

✓ Name project3
✓ Description alice 3
✓ Default branch main
✓ Project project3 created
✓ Syncing inventory..

Your project id is rad:z42Q64chcGUSgcYHmNwG2DTyrSy8H. You can show it any time by running:
    rad .

To publish your project to the network, run:
    rad push

```

2. Now clone the repo in a different folder and make some changes and commit them: 

```bash
23-03-22 10:09 ➜  project3 git:(main) cd ../
23-03-22 10:10 ➜  alice mkdir tmp
23-03-22 10:10 ➜  alice cd tmp
23-03-22 10:10 ➜  tmp rad clone rad:z42Q64chcGUSgcYHmNwG2DTyrSy8H
! Warning: No seeds found, local copy is potentially stale
✓ Creating checkout in ./project3..

🌱 Project successfully cloned under /Users/yorgos/dev/playground/web3/radicle/playtime/alice/tmp/project3/

23-03-22 10:10 ➜  tmp cd project3
23-03-22 10:10 ➜  project3 git:(main) vi README.md
23-03-22 10:10 ➜  project3 git:(main) ✗ git add .
23-03-22 10:10 ➜  project3 git:(main) ✗ git commit -m 'takis'
[main 0b1994c] takis
 1 file changed, 2 insertions(+)
23-03-22 10:10 ➜  project3 git:(main) git push rad
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Writing objects: 100% (3/3), 446 bytes | 446.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Announcing refs... ok
To rad://z42Q64chcGUSgcYHmNwG2DTyrSy8H/z6MksXZovp72RijoDZ1zKyePzTYdJo5JdEfChYCUH6vMJpaH
   d2e3e57..0b1994c  main -> main
```

3. Now switch back to the original project and pull the changes:

```bash
23-03-22 10:10 ➜  project3 git:(main) cd ../../project3
23-03-22 10:10 ➜  project3 git:(main) git status
On branch main
Your branch is up to date with 'rad/main'.

nothing to commit, working tree clean
23-03-22 10:10 ➜  project3 git:(main) git fetch
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 426 bytes | 213.00 KiB/s, done.
From rad://z42Q64chcGUSgcYHmNwG2DTyrSy8H/z6MksXZovp72RijoDZ1zKyePzTYdJo5JdEfChYCUH6vMJpaH
   d2e3e57..0b1994c  main       -> rad/main
23-03-22 10:10 ➜  project3 git:(main) git pull
Updating d2e3e57..0b1994c
Fast-forward
 README.md | 2 ++
 1 file changed, 2 insertions(+)
```

This all uses the `rad` remote and we just rely on `git` and the `radicle-remote-helper`. 

@JChrist / @Stelios123 am I missing something ?

**Comment by JChrist** [comment]
I totally agree.
This is something I was thinking about the functionality of push, as well, for #191. 
The local radicle node already takes care of automatic syncing, so rad pull/push seems obsolete and git pull/push is needed only.

**Comment by gsaslis** [comment]
> The local radicle node already takes care of automatic syncing, so rad pull/push seems obsolete and git pull/push is needed only.

@JChrist I thought that was _almost_ true and `rad push` was the one that set up the `rad` git remote and actually published the project to the network (as promised [here](https://github.com/radicle-dev/heartwood/blob/master/radicle-cli/src/commands/push.rs#L13)), but - looking at the code - I don't actually see that to be the case.

**Comment by gsaslis** [comment]
I've asked in zulip.

**Comment by gsaslis** [comment]
p.s. regarding: 

> I've asked in zulip.

the outcome was that `rad pull` might well be removed. 

I would like us to remove it from the IDE so we don't create further confusion like "why are there 2 buttons called 'pull' (rad pull + git pull), if they both do the same"
