### ISSUE TITLE
Migrate Radicle -> sync to heartwood

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#193]
`Radicle -> Sync` should be **replaced** with `Radicle -> Fetch`. 

Pre-heartwood, `rad sync` both pushed new refs to the seed node as well as pulled in new refs from the seed. On heartwood, we can: 

- push changes to the network with just `rad push` ( it used to be the case that `rad push` == `git push rad && rad sync` - but on heartwood the gossip protocol takes care of the `rad sync` part)
- get latest changes from the network with `rad fetch` 
 

~This functionality looks like it is no longer needed, so we need to figure out how to achieve the same result: show the user, within the IDE, that their node is in sync with the network (if possible).~

**Comment by gsaslis** [comment]
@Stelios123 / @JChrist I have updated the ticket description with the changes I think are necessary here. Please take a look and let me know if you have any comments / questions / etc.

**Comment by Stelios123** [comment]
So here we replace Sync with `rad fetch` command?
