### ISSUE TITLE
Make radicle plugin settings projectConfigurable as opposed to applicationConfigurable

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#206]
We should have the path to `RAD_HOME` as a project-specific setting. 
The path to the `rad` binary can probably stay an application wide setting. 

https://plugins.jetbrains.com/docs/intellij/settings-guide.html#declaring-project-settings

**Comment by Stelios123** [comment]
Maybe here we can add also a checkbox like `GitHub` 

![Image](https://user-images.githubusercontent.com/31673488/228758430-47061c64-a3ea-4b06-b40b-01a229a1a1d0.png)

So if the user checks the icon then the RAD_HOME will be for the specific project, if not the RAD_HOME will be global 

@gsaslis what do you think ?

**Comment by gsaslis** [comment]
@Stelios123 for 0.4 I would like us to **keep** `RAD_HOME` as a project-specific setting **only**.

There might be changes coming up in identity (and `RAD_HOME`), so I'd rather we didn't invest any more time here - yet. 
Please don't get me wrong - this makes _perfect_ sense for the future - after the dust around identity / storage has settled (e.g. the [PR for storage](https://github.com/radicle-dev/rips/pull/1) still isn't merged).   

Let's move forward without this right now.

**Comment by Stelios123** [comment]
ok
