### ISSUE TITLE
Add Radicle category & items in Action Toolbar

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#21]
The action toolbar is the 2nd place where we expect to see Radicle actions - just like git actions also show up. 

We should include radicle sections within the Git category, if possible (i.e. we don't need another separator), like shown below:

<img width="1397" alt="Screenshot 2022-07-19 at 7 31 26 AM" src="https://user-images.githubusercontent.com/2420882/179672457-74858f57-4bd0-44bd-a3e0-42b6f13c9fd2.png">

<img width="1306" alt="Screenshot 2022-07-19 at 7 28 18 AM" src="https://user-images.githubusercontent.com/2420882/179672234-dfba1f9c-78c9-49b0-88ad-107e73bb6204.png">

**Comment by gsaslis** [comment]
> For the first action (rad sync) I suspect that we want to show the git push dialog to the user and after the push, we will run
> rad sync.
> For the second action (rad pull) we want to run rad pull and show a notification.
> For the third, I am not so sure. Maybe just run rad push and show a notification like the second action?

The actions / behaviour is exactly as the menu items. 
🤔 are you saying we haven't defined that already ?

> So here we need 3 icons 

@micmeistudio could you perhaps help us create those ?

**Comment by micmeistudio** [comment]
Hello @Stelios123! I'm attaching some icons. Please share a screenshot when you apply it to see how it looks like.  
[icons.zip](https://github.com/cytechmobile/radicle-jetbrains-plugin/files/9180024/icons.zip)

**Comment by Stelios123** [comment]
thanks

**Comment by Stelios123** [comment]
![image](https://user-images.githubusercontent.com/31673488/180804638-92f291c7-86d3-4aa2-9154-72c21953844b.png)

**Comment by micmeistudio** [comment]
Nice @Stelios123 ,maybe the radicle sync needs to darken a little bit. I'm sending you an alternative. Thanks!
![Rad Sync](https://user-images.githubusercontent.com/58848466/181228428-c2f4443d-f02a-4a26-9c10-94e13f13533d.svg)

**Comment by gsaslis** [comment]
@Stelios123 should we remove / hide the pull icon , as we're focusing on push and sync in this iteration ?

@micmeistudio I am wondering if we should (or shouldn't) follow the git icons for our own actions... 🤔 

`git push` and `git pull` both have specific icons (the diagonal-up and diagonal-down arrows respectively), so I wonder if `rad push` and `rad pull` shouldn't just follow the same patterns.. ?

also, considering there is no "radicle" separator, how would the user know that those are radicle-specific ?

**Comment by micmeistudio** [comment]
@gsaslis We can follow the existing icons with the text on the left like "Git:" "Radicle:". Actually are the same actions. The user can see git and radicle actions at the same time? Git i think is by default? On the other hand if we have at the same time actions from Git and Radicle then Radicle alternate icons maybe will be easier stand out. I think it's all about testing :) and getting feedback from the users.

**Comment by gsaslis** [comment]
> We can follow the existing icons with the text on the left like "Git:" "Radicle:". 

If you mean adding an extra text label with "Radicle:", then I think that would take up too much real estate for little benefit. IMHO, it makes sense to have them in the Git section. 

> Actually are the same actions. 

They _do_ have same/similar names, but it's not exactly the same action. 

> The user can see git and radicle actions at the same time? 

Yes, they can.

> On the other hand if we have at the same time actions from Git and Radicle then Radicle alternate icons maybe will be easier stand out.

Perhaps the radicle icon (from https://radicle.xyz/brand ) could be made part of the push/pull/sync icons?

**Comment by micmeistudio** [comment]
@gsaslis Ok so let's make specific icons for Radicle. I'm attaching some alternatives icons.
[ASSETS.zip](https://github.com/cytechmobile/radicle-jetbrains-plugin/files/9219818/ASSETS.zip)

**Comment by gsaslis** [comment]
cool, thanks @micmeistudio ! 

@Stelios123 could you please add these so we can take another look ? 🙏

**Comment by Stelios123** [comment]
![image](https://user-images.githubusercontent.com/31673488/182606487-5ef4ea84-885d-40a7-b3b1-5530d27bb583.png)
