### ISSUE TITLE
Add/edit/delete comments on patch proposals (editor tab)

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#225]
This issue is about adding functionality that allows users to add/edit/delete comments to patch proposals, directly from their IDE: 

* adding new comments (through a text input field at the very end of the activity / conversation) 
* editing existing comments 
* delete existing comments
* a user should only be allowed to edit/delete their own comments by our app 

![Image](https://user-images.githubusercontent.com/2420882/230923693-31f3552c-0b2f-44a9-bbe3-62a5e26bbad5.png)

![Image](https://user-images.githubusercontent.com/2420882/230923709-c6bafcf6-0644-446d-a348-1de5897d2abf.png)

**Comment by Stelios123** [comment]
We don't know if edit / delete functionality exists yet so the Days are only for Add

**Comment by Stelios123** [comment]
Right now there is no edit / delete functionality 

![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/2a82779a-8688-4c2d-a8b5-14117674024e)

**Comment by gsaslis** [comment]
@Stelios123 and does the API not support it either?

**Comment by Stelios123** [comment]
No there isn't a API for this
