### ISSUE TITLE
Clickable commit hashes in patch proposal conversation view

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#227]
On the conversation view of the patch proposal, the timeline of events also shows commits. 

This issue is about making the commit hashes clickable. 
Upon clicking on the commit, the user will be taken from the "Activity" tab to the "Commits" tab of the Patch Proposal component, with the specific commit selected.

**Comment by Stelios123** [comment]
Result

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/6f431eb2-27d7-4ae2-8379-b5576452b28b
