### ISSUE TITLE
Handle special characters in patch proposal title

### ISSUE THREAD

**Issue by Stelios123** [cytechmobile/radicle-jetbrains-plugin#251]
this affects all cli commands that use arbitrary user input (e.g. comments, etc. ) 

We are consider moving these to the API.

**Comment by gsaslis** [comment]
@JChrist / @Stelios123 can we please list all the affected commands here, so we can break down the remaining effort ? This is affecting the release of 0.5

**Comment by Stelios123** [comment]
`rad patch open --message "Define power requirements" --message "See details."`
`rad comment 077e4bbe9a6e5546f400ef5951768c37a76f13a4 --message 'Hello'`

Currently, we have a problem with the `--message` parameter and we are looking for a way to escape the special characters (Only for Windows OS).

We have two ways to bypass this problem 

- Make an API request
- Save somewhere the commands that we want to run and then run this file from wsl.

I think we have to implement both solutions because currently there isn't a comment API that I can use. @JChrist  what do you think?

**Comment by gsaslis** [comment]
thanks @Stelios123 

from my point of view, we can keep this as a known bug and ask the heartwood team when they expect the API endpoint can be added - which will open the path to solving this properly (through API requests).

**Comment by gsaslis** [comment]
UPDATE: 

turns out _there is_ an HTTP API endpoint to do this. 

I've created #264 and #265 that will also help resolve this issue here.
