### ISSUE TITLE
Rebrand to new radicle identity

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#269]
Replace all icons with new radicle brand identity ones

need icons also for editor tab: 
- patches 
- issues

**Comment by gsaslis** [comment]
new assets: https://radworks.org/brand

**Comment by Stelios123** [comment]
Result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/bcb3ad42-eb3d-4b57-a8c4-95de4b794d8e
