### ISSUE TITLE
Comment reactions (in Patches / Issues)

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#270]
It should be possible to react to comments with an emoji.

**Comment by Stelios123** [comment]
The cli doesn't implement the functionality to remove reactions from the issue or add a new reaction to patch comments. So this issue is on stand by I guess?

**Comment by gsaslis** [comment]
@Stelios123 what about the API?

**Comment by Stelios123** [comment]
I meant from API

**Comment by gsaslis** [comment]
ok, I'll move this back to "Up Next" and we revisit in a couple of weeks.
