### ISSUE TITLE
Editing comments in Patches

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#272]
It would be nice to be able to edit comments for typos, etc.

**Comment by Stelios123** [comment]
I can't continue with this because there is no such functionality in cli yet

**Comment by gsaslis** [comment]
@Stelios123 are we not using the API for this? perhaps the functionality is available there?

**Comment by Stelios123** [comment]
sorry i meant from API

**Comment by gsaslis** [comment]
moving to backlog for now

**Comment by Stelios123** [comment]
I changes the issue to editing comments in patches and i created a new one for issues

**Comment by Stelios123** [comment]
result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/f2de1bb2-5d63-473f-9214-c4f4e90d752c
