### ISSUE TITLE
Run rad commands in windows machine without asking for passphrase

### ISSUE THREAD

**Issue by Stelios123** [cytechmobile/radicle-jetbrains-plugin#30]

**Comment by Stelios123** [comment]
**Windows users with wsl **

- Open wsl 
- Install keychain `sudo apt install keychain`
- Then add the following line to your shell configuration (~/.bashrc or ~/.zshrc) 
`eval `keychain --quiet --eval --agents ssh id_rsa`
- Run `rad auth` in your project directory

**Comment by gsaslis** [comment]
Added these to #34
