### ISSUE TITLE
Remove reaction from patches/ issue comments

### ISSUE THREAD

**Issue by Stelios123** [cytechmobile/radicle-jetbrains-plugin#326]

**Comment by Stelios123** [comment]
Result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/7bb045b1-1667-4084-bf09-f566cd635bf3

**Comment by gsaslis** [comment]
@Stelios123 looks like this always reloads the whole issue... 

Should I create a new issue for later, to make this happen without refreshing the page?
