### ISSUE TITLE
Wrap title / description in patches / issues overview

### ISSUE THREAD

**Issue by Stelios123** [cytechmobile/radicle-jetbrains-plugin#335]
We need to probably use some kind of textarea that also takes care of markdown formatting. 

This way the content would also have a fixed length - but, ideally, the textarea could also be resized. 

See screenshots below for some problematic examples: 

![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/2420882/10d28aed-3d64-4323-a6c7-51eb8ddedc57)

![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/2420882/caee4c0f-369a-4c13-97d8-13ba9dacd3aa)

**Comment by gsaslis** [comment]
@Stelios123 relevant thread https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004558960-Markdown-text-rendering-in-a-plugin

**Comment by gsaslis** [comment]
@Stelios123 this is NOT done, I'm afraid, as there is no support for markdown formatting.

**Comment by Stelios123** [comment]
result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/05205fe0-dfef-48cd-adde-187c62b50c6d
