### ISSUE TITLE
Memory Leaked

### ISSUE THREAD

**Issue by Stelios123** [cytechmobile/radicle-jetbrains-plugin#340]
Steps to reproduce: 

1. Open a patch proposal or issue
2. Close the editor
3. Close the intellij

**Comment by gsaslis** [comment]
@Stelios123 can you please also include in the steps how I can verify that memory is being leaked?

also, can you assign a size and let me know once you have, so I can move back to "up next" ?

**Comment by gsaslis** [comment]
closing this as it looks to have gone away.
