### ISSUE TITLE
IDE Internal Error

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#362]
An error is thrown while navigating patches:

![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/1916797/4b9cdc39-4298-4bb7-895f-a76bb257e16f)

**Comment by gsaslis** [comment]
@JChrist how often does this happen on your machine ?

**Comment by JChrist** [comment]
I just saw it, it hasn't ocurred before.

**Comment by JChrist** [comment]
This seems to be a real issue, it's now occuring almost every time I open the rtw patches. IIUC, it happens the first time I open the patches window and does not occur again (or is not reported again) until ide restart.
@gsaslis I think it should become priority.

**Comment by gsaslis** [comment]
@JChrist thanks - that makes sense. 

Any idea what sort of sign we can assign here?

**Comment by JChrist** [comment]
We have a stacktrace, so there's a good enough hint on where the issue lies (still needs investigation on why though).
I added sizing based on that.

**Comment by gsaslis** [comment]
thanks ! moved to "Up Next"

**Comment by Stelios123** [comment]
I think I fixed that in CreatePatch branch. The main reason for the error was that the function `fetchPeerChanges` was not cancelable. Check here https://github.com/cytechmobile/radicle-jetbrains-plugin/blob/bafcefbb0bf4472f7feba6a8fa14d4d7c57a1e51/src/main/java/network/radicle/jetbrains/radiclejetbrainsplugin/services/RadicleProjectService.java#L121

**Comment by JChrist** [comment]
confirmed as fixed in v0.8.0 via #397
