### ISSUE TITLE
Adding / removing reactions shouldn't refresh/re-render the whole page

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#363]
Whenever I add or remove a reaction, the editor tab reloads. 

It would be great if it didn't need to and I could just see the added reaction without re-rendering the whole page but just the specific component.

**Comment by gsaslis** [comment]
@Stelios123 / @JChrist can you please add an estimated size here?

**Comment by Stelios123** [comment]
Result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/f2e6f567-376e-4f7f-a251-7c3121b98d51
