### ISSUE TITLE
Inline comments / discussions for patches

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#365]
This issue is about supporting inline comments in patches, so it becomes possible to review individual code lines. ( `RevisionComment` in the radicle-httpd API )

We should have the ability to start inline discussions on a specific line (what github calls "add single comment").

We should also be able to reply to those inline comments. 

Out of scope: 

- "resolving" conversations  
- We do not need support for "suggestions" yet.

**Comment by Stelios123** [comment]
Result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/8f42a52d-7283-4a50-9b70-379643cc8dc4
