### ISSUE TITLE
Patch proposal review

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#367]
Add a way to show patch proposal reviews (accept/reject), along with comments.

This review might be for the whole patch proposal, or for individual hunks.

**Comment by gsaslis** [comment]
Relevant API endpoint `/projects/{rid}/patches/{patch}`
 

- https://app.radicle.xyz/nodes/seed.rhizoma.dev/rad:z3yQUb9HDAC7TQrUDGkQsXDsYFj9G/tree/api/radicle-httpd.yaml#L542
- https://app.radicle.xyz/nodes/seed.rhizoma.dev/rad:z3yQUb9HDAC7TQrUDGkQsXDsYFj9G/tree/api/radicle-httpd.yaml#L1404

**Comment by Stelios123** [comment]
![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/9657a8fc-00a9-4f5f-bf85-586b521f9a3c)
