### ISSUE TITLE
Support attachments in issue/patch comments

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#371]
We should be able to attach and display files (e.g. screenshots/pictures) to the issue/patch comments/descriptions. 

we should at least support: 

- pictures 
- videos (for screen recordings)

**Comment by Stelios123** [comment]
At the moment we can't support attachments in patch creation. It is not supported by httpd yet

**Comment by gsaslis** [comment]
@Stelios123 can you please link a zulip topic where this has been discussed, so it's clear that the httpd maintainers are aware of the issue?

**Comment by Stelios123** [comment]
https://radicle.zulipchat.com/#narrow/stream/369277-heartwood/topic/Attachments.20in.20patches

**Comment by Stelios123** [comment]
Result : 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/162649d0-5ef8-4e48-a090-347db38e8ba5

**Comment by gsaslis** [comment]
Great stuff @Stelios123 ! 👏🏼
