### ISSUE TITLE
Patch proposal checkout error

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#385]
Attempting to checkout a patch proposal that is already checked out results in error:

![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/1916797/5fe2e042-d817-49fe-a2c7-259b2e936b52)

**Comment by gsaslis** [comment]
@JChrist can you please also add an estimated size here, so we can prioritise accordingly?
