### ISSUE TITLE
Patch status

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#395]
I am able to change patch status, even for merged patches.
But, I cannot re-set them as merged (this is probably OK).
So, I am left with a merged patch that is open and cannot be re-merged.

![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/1916797/470b269f-5d05-452f-a6d1-77a59e25fa74)

We should disable the status edit button when the patch is already merged and - for bonus points - also show a tooltip.

**Comment by gsaslis** [comment]
@JChrist please also write a quick message in zulip about this to report to core team to have this fixed in httpd as well.
