### ISSUE TITLE
Patch description is not displayed in its own designated area, but inside the first revision

### ISSUE THREAD

**Issue by Stelios123** [cytechmobile/radicle-jetbrains-plugin#401]
The patch description is not displayed in its own designated area, but inside the first revision object.

**Comment by gsaslis** [comment]
@Stelios123 can you please add a description and size here ?

**Comment by JChrist** [comment]
I want to add here that further revisions show again all the commits from the first revision plus the new commits.
Perhaps it would make sense to filter these out.
For example, let's assume I'm creating a patch with commits: A, B and C. Then (e.g. after review), I add commit D.
This will show revision 1 with commits A, B and C and revision 2 with commits: A, B, C and D.

**Comment by gsaslis** [comment]
@JChrist to be honest, I still don't understand what this issue is about. Is it about the list of commits per revision?

**Comment by JChrist** [comment]
The initial reported issue is that the patch description is not displayed in its own designated area, but inside the first revision object.

My added issue is very different, so perhaps it can be moved out to another issue, is about the list of commits per revision.

**Comment by gsaslis** [comment]
Created #404 for that so we can focus on the original issue here. Leaving the `needs refinement` label until we have a clearer picture of size, etc.
