### ISSUE TITLE
Format revision descriptions and commit messages as markdown

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#407]
* markdown should be supported in all these
* for commit messages, show title separately, if there is one. 
* show in patch description the latest revision description that is non-empty.

**Comment by Stelios123** [comment]
After a conversation that I had with @gsaslis, we said that the Patch overview page needs to have only the date/time that a revision was published. This means that the commits should be removed from the page.
