### ISSUE TITLE
Issue date created is wrong format

### ISSUE THREAD

**Issue by Stelios123** [cytechmobile/radicle-jetbrains-plugin#447]
![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/31673488/79ac5846-4165-4af2-b285-0f47e829d406)

**Comment by JChrist** [comment]
this is fixed in main:


![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/1916797/e702e1e7-70d3-4784-bdf6-6b2d04fc9b04)
