### ISSUE TITLE
Issues view not populated the first time the plugin is open

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#455]
The Issues view in the Radicle Tool Window is empty until I refresh. I created a screen recording to illustrate. 

https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/2420882/d5efcf6f-e497-453d-893f-5aea3a234473

**Comment by JChrist** [comment]
I can't reproduce this on Linux with plugin 0.8.2 on IntelliJ IDEA 2023.3.3
Is there something else that you can add to make it reproducible?

**Comment by Stelios123** [comment]
This issue is resolved and already merged into main (https://github.com/cytechmobile/radicle-jetbrains-plugin/pull/456)
