### ISSUE TITLE
RTW Patch View appears off

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#461]
- The patch description in the left side is not well-formatted and has the same font as the title.
- The view timeline and checkout buttons appear in the middle of nowhere
~- The timeline does not show any commit information for the revisions~
- Clicking on the patch id in the timeline shows a "browser error" message (screenshot 2)

![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/1916797/b3208c73-eee2-4e73-8c97-d7af98e5a735)

![Image](https://github.com/cytechmobile/radicle-jetbrains-plugin/assets/1916797/7c0f4ef4-6471-4c43-bec0-c84b2f763319)

**Comment by gsaslis** [comment]
Pending: 

- - show first e.g. 100 chars in description with `...` 
- no markdown necessary here
- if the latest revision does not have a description, show the latest that does have one. 
- change text from "View Timeline" to "Open in Editor"
