### ISSUE TITLE
Show comments from all revisions

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#509]
In the timeline, I can see comments from all revisions. 

But when reviewing the diff, I can't see comments from non-latest revision. This has the problem that when adding a new commit e.g. to fix one of the inline comments, I can no longer see the comment (even if the commit changed an unrelated line). 

Cases: 

- a comment is left on a line that is not changed in a subsequent revision (the diff remains the same)
- a comment is left on a line that is later changed in a following commit
- a comment is left on a line in a file that is later deleted
- a comment is left on a line in a file that is renamed 
- a comment is edited

**Comment by gsaslis** [comment]
1. let's add `commented on $path:$line_number (outdated)` in the overall timeline view
2. we won't show comments that are in cases 2,3,4 for now (because they can be seen in the timeline view - and the diff view will just show latest changes)

**Comment by Stelios123** [comment]
I perform a test to measure the time required to render comments. There were a total of 25 comments, of which 17 were outdated and 8 were current on the latest revision. The rendering process took 3.5 seconds

**Comment by gsaslis** [comment]
@Stelios123 having this _working_ - even if it takes a few seconds - is certainly an improvement over not having it at all - which is blocking proper code reviews (which is a major issue). 

Let's move forward and we can come back in the future to improve performance here.

**Comment by Stelios123** [comment]
Ok we will continue with the merge
