### ISSUE TITLE
confirm httpd version compatibility in settings

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#525]
when the "Test" button is clicked, we should check that we have a compatible httpd version.

**Comment by gsaslis** [comment]
We need to define a version range in the plugin of known-compatible versions of the HTTP API.

**Comment by JChrist** [comment]
Given [this discussion in zulip](https://radicle.zulipchat.com/#narrow/stream/369278-web/topic/moving.20httpd.20to.20the.20radicle-explorer.20repo), this might not be needed.

**Comment by gsaslis** [comment]
@JChrist we still need this now, considering the change is "months" away.

**Comment by gsaslis** [comment]
We want to check the `apiVersion` field rather than the `version`.
