### ISSUE TITLE
Git -> Radicle -> Publish

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#61]

**Comment by Stelios123** [comment]
can you remind me about this task ?

**Comment by gsaslis** [comment]
@Stelios123 this is the action someone would invoke in order to publish their repo to radicle for the first time.

**Comment by gsaslis** [comment]
It needs to check if the project has already been `rad init` -ed :

* if it hasn't it brings up the radicle -> init dialog : https://www.figma.com/proto/9h2suLnyckUXGmMyReMiYP/LF-Wireframe---Milestone-1?node-id=472119%3A15937&scaling=contain&page-id=77%3A432&starting-point-node-id=472119%3A11764&show-proto-sidebar=1
* once it has been initialised: https://www.figma.com/proto/9h2suLnyckUXGmMyReMiYP/LF-Wireframe---Milestone-1?node-id=472119%3A15350&scaling=contain&page-id=77%3A432&starting-point-node-id=472119%3A11764&show-proto-sidebar=1

**Comment by gsaslis** [comment]
If a project hasn't been initialised, the Radicle sub-menu will **only** show: "Share Project on Radicle". 

That brings up a single dialog with the necessary fields for `rad init` + the seed node, so that the project can be pushed. 

Once a project has been initialised, the Radicle sub-menu shouldn't show this option again.
