### ISSUE TITLE
Toolbar icons don't show on MacOS / 2021.3

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#62]
After installing the plugin, the toolbar icons are not visible on some IntelliJ versions. 

<img width="874" alt="Screenshot 2022-08-17 at 10 05 40 AM" src="https://user-images.githubusercontent.com/2420882/185063001-5389a927-93e1-4b04-9e6f-9e1f1e881320.png">

However, the menu items appear normally: 

<img width="800" alt="Screenshot 2022-08-17 at 10 30 38 AM" src="https://user-images.githubusercontent.com/2420882/185062978-f30914bb-4d7d-49e4-a8cb-c2ad641d711a.png">
<img width="1093" alt="Screenshot 2022-08-17 at 10 07 53 AM" src="https://user-images.githubusercontent.com/2420882/185062988-d3270e27-635c-4797-8c30-8ff1814d24dd.png">

**Comment by Stelios123** [comment]
You have to uncheck the toolbar from View -> Appearance

**Comment by gsaslis** [comment]
Hmm I see that does work indeed @Stelios123 ! Thanks! 

Question is: why does it work? Is the "toolbar" something else than where we inserted the actions? 

I see Git actions in both. Can we have the same for Radicle?

**Comment by gsaslis** [comment]
reopening as I think we still need answers to the above questions.

**Comment by Stelios123** [comment]
ok let me see

**Comment by Stelios123** [comment]
Done

**Comment by gsaslis** [comment]
@Stelios123 hmmm perhaps you can link this to the PR were the issue was closed? 

It is not obvious to me how it was fixed.
