### ISSUE TITLE
Add name to list of identities

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#90]
as per https://github.com/radicle-dev/radicle-cli/issues/255 

let's enrich our list of identities to also show the profile name

**Comment by Stelios123** [comment]
To get the name of the identities i have to read it from storage and i think this is gonna change in future release so i dont think its good idea to implement this right now.

**Comment by gsaslis** [comment]
@Stelios123 Maybe I misread the issue / PR I linked to, but it seems to me that the name has already been added in the latest cli version, no?

**Comment by Stelios123** [comment]
in rad 0.6.1 i dont see the names with rad auth, i see only identities. Also i cant use rad auth because after the command i have to choose for identity, this will not work from the plugin.

**Comment by gsaslis** [comment]
apologies, I meant the latest _development_ version of the CLI.

**Comment by gsaslis** [comment]
After chatting about this live, our current problem is that `rad auth` doesn't offer non-interactive output. Because of this, even if it returns the name, we can't really read it from there.

**Comment by gsaslis** [comment]
I created https://github.com/radicle-dev/radicle-cli/issues/269 to ask for assistance from radicle clients folks.

**Comment by gsaslis** [comment]
@Stelios123 / @JChrist looks like this issue is no longer relevant?

Please close if so. ;)
